# Generated by Django 4.1.4 on 2023-02-15 17:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative_divisions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, default='default/blank_profile.webp', upload_to='images/profile')),
                ('father_first_name', models.CharField(max_length=30)),
                ('father_middle_name', models.CharField(blank=True, default=None, max_length=30)),
                ('father_last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('CNIC', models.CharField(max_length=13)),
                ('CNIC_picture', models.ImageField(blank=True, default='default/blank_cnic.jpg', upload_to='images/CNIC')),
                ('phone', models.CharField(max_length=11)),
                ('education', models.CharField(max_length=300)),
                ('occupation', models.CharField(max_length=300)),
                ('current_address', models.CharField(max_length=300)),
                ('permanent_address', models.CharField(max_length=300)),
                ('halqa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrative_divisions.halqa')),
            ],
        ),
    ]
