# Generated by Django 4.1.4 on 2023-02-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='halqa',
        ),
    ]
