# Generated by Django 4.1.4 on 2023-02-15 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative_divisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_first_name', models.CharField(max_length=30)),
                ('father_middle_name', models.CharField(blank=True, max_length=30)),
                ('father_last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('CNIC', models.CharField(max_length=13)),
                ('quality', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=255)),
                ('halqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_divisions.halqa')),
            ],
        ),
    ]
