# Generated by Django 4.1.4 on 2023-03-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectrary',
            fields=[
                ('teacher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teachers.teacher')),
            ],
            bases=('teachers.teacher',),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='reason',
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_appointement',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
