# Generated by Django 4.1.4 on 2023-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_sectrary_remove_teacher_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='date_of_appointement',
            new_name='date_of_appointment',
        ),
    ]
