# Generated by Django 4.1.4 on 2023-02-15 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('president', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('president', models.CharField(default='', max_length=60)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_divisions.province')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('president', models.CharField(default='', max_length=60)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_divisions.region')),
            ],
        ),
        migrations.CreateModel(
            name='Halqa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('president', models.CharField(default='', max_length=60)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_divisions.zone')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('president', models.CharField(default='', max_length=60)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative_divisions.region')),
            ],
        ),
    ]
